export enum ELocalStorageKeys{
    ID_SELECTED_TASKTYPE = "ID_SELECTED_TASKTYPE",
    ID_SELECTED_TASK = "ID_SELECTED_TASK",
    ID_CHRONOMETER = "ID_CHRONOMETER",
    ID_ACTIVE_NOTIFICATION = " ID_ACTIVE_NOTIFICATION",
    CLOCK_STATUS = "CLOCK_STATUS",
    ID_TIMER = "ID_TIMER"
    
}